name: dart_extensions
description: Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 2.3.0
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  quiver: ^3.2.1
  http: ^1.1.0
  recase: ^4.1.0
  timeago: ^3.5.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
